/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseTeamDto,
  TeamCreateRequest,
  TeamJoinRequest
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const createTeam = (
    teamCreateRequest: TeamCreateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseTeamDto>(
      {url: `/teams`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: teamCreateRequest, signal
    },
      options);
    }
  


export const getCreateTeamMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeam>>, TError,{data: TeamCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createTeam>>, TError,{data: TeamCreateRequest}, TContext> => {

const mutationKey = ['createTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTeam>>, {data: TeamCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTeam(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTeamMutationResult = NonNullable<Awaited<ReturnType<typeof createTeam>>>
    export type CreateTeamMutationBody = TeamCreateRequest
    export type CreateTeamMutationError = unknown

    export const useCreateTeam = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeam>>, TError,{data: TeamCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTeam>>,
        TError,
        {data: TeamCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const joinTeam = (
    teamJoinRequest: TeamJoinRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseTeamDto>(
      {url: `/teams/join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: teamJoinRequest, signal
    },
      options);
    }
  


export const getJoinTeamMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinTeam>>, TError,{data: TeamJoinRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof joinTeam>>, TError,{data: TeamJoinRequest}, TContext> => {

const mutationKey = ['joinTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof joinTeam>>, {data: TeamJoinRequest}> = (props) => {
          const {data} = props ?? {};

          return  joinTeam(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type JoinTeamMutationResult = NonNullable<Awaited<ReturnType<typeof joinTeam>>>
    export type JoinTeamMutationBody = TeamJoinRequest
    export type JoinTeamMutationError = unknown

    export const useJoinTeam = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinTeam>>, TError,{data: TeamJoinRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof joinTeam>>,
        TError,
        {data: TeamJoinRequest},
        TContext
      > => {

      const mutationOptions = getJoinTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getMyTeam = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseTeamDto>(
      {url: `/teams/my-team`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyTeamQueryKey = () => {
    return [
    `/teams/my-team`
    ] as const;
    }

    
export const getGetMyTeamQueryOptions = <TData = Awaited<ReturnType<typeof getMyTeam>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyTeamQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyTeam>>> = ({ signal }) => getMyTeam(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyTeam>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyTeamQueryResult = NonNullable<Awaited<ReturnType<typeof getMyTeam>>>
export type GetMyTeamQueryError = unknown


export function useGetMyTeam<TData = Awaited<ReturnType<typeof getMyTeam>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyTeam>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyTeam>>,
          TError,
          Awaited<ReturnType<typeof getMyTeam>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyTeam<TData = Awaited<ReturnType<typeof getMyTeam>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyTeam>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyTeam>>,
          TError,
          Awaited<ReturnType<typeof getMyTeam>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyTeam<TData = Awaited<ReturnType<typeof getMyTeam>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyTeam<TData = Awaited<ReturnType<typeof getMyTeam>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyTeamQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



