/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseRaceSequenceDto,
  RaceSequenceSaveRequest
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const saveOrUpdateSequence = (
    raceSequenceSaveRequest: RaceSequenceSaveRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseRaceSequenceDto>(
      {url: `/sequences`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: raceSequenceSaveRequest, signal
    },
      options);
    }
  


export const getSaveOrUpdateSequenceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveOrUpdateSequence>>, TError,{data: RaceSequenceSaveRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saveOrUpdateSequence>>, TError,{data: RaceSequenceSaveRequest}, TContext> => {

const mutationKey = ['saveOrUpdateSequence'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveOrUpdateSequence>>, {data: RaceSequenceSaveRequest}> = (props) => {
          const {data} = props ?? {};

          return  saveOrUpdateSequence(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SaveOrUpdateSequenceMutationResult = NonNullable<Awaited<ReturnType<typeof saveOrUpdateSequence>>>
    export type SaveOrUpdateSequenceMutationBody = RaceSequenceSaveRequest
    export type SaveOrUpdateSequenceMutationError = unknown

    export const useSaveOrUpdateSequence = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveOrUpdateSequence>>, TError,{data: RaceSequenceSaveRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveOrUpdateSequence>>,
        TError,
        {data: RaceSequenceSaveRequest},
        TContext
      > => {

      const mutationOptions = getSaveOrUpdateSequenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const initiateSequence = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseRaceSequenceDto>(
      {url: `/sequences/${id}/initiate`, method: 'POST', signal
    },
      options);
    }
  


export const getInitiateSequenceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initiateSequence>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof initiateSequence>>, TError,{id: string}, TContext> => {

const mutationKey = ['initiateSequence'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initiateSequence>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  initiateSequence(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InitiateSequenceMutationResult = NonNullable<Awaited<ReturnType<typeof initiateSequence>>>
    
    export type InitiateSequenceMutationError = unknown

    export const useInitiateSequence = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initiateSequence>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof initiateSequence>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getInitiateSequenceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getActiveSequence = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseRaceSequenceDto>(
      {url: `/sequences/active`, method: 'GET', signal
    },
      options);
    }
  



export const getGetActiveSequenceQueryKey = () => {
    return [
    `/sequences/active`
    ] as const;
    }

    
export const getGetActiveSequenceQueryOptions = <TData = Awaited<ReturnType<typeof getActiveSequence>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveSequence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActiveSequenceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveSequence>>> = ({ signal }) => getActiveSequence(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActiveSequence>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActiveSequenceQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveSequence>>>
export type GetActiveSequenceQueryError = unknown


export function useGetActiveSequence<TData = Awaited<ReturnType<typeof getActiveSequence>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveSequence>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveSequence>>,
          TError,
          Awaited<ReturnType<typeof getActiveSequence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveSequence<TData = Awaited<ReturnType<typeof getActiveSequence>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveSequence>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveSequence>>,
          TError,
          Awaited<ReturnType<typeof getActiveSequence>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActiveSequence<TData = Awaited<ReturnType<typeof getActiveSequence>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveSequence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetActiveSequence<TData = Awaited<ReturnType<typeof getActiveSequence>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActiveSequence>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActiveSequenceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



