/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RaceSequenceDto } from './raceSequenceDto';

export interface ApiResponseRaceSequenceDto {
  success?: boolean;
  message?: string;
  result?: RaceSequenceDto;
}
