/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AuthResponse } from './authResponse';

export interface ApiResponseAuthResponse {
  success?: boolean;
  message?: string;
  result?: AuthResponse;
}
