/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TeamDto } from './teamDto';

export interface ApiResponseTeamDto {
  success?: boolean;
  message?: string;
  result?: TeamDto;
}
