/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DriverDto } from './driverDto';

export interface ApiResponseDriverDto {
  success?: boolean;
  message?: string;
  result?: DriverDto;
}
