/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CircuitDto } from './circuitDto';

export interface ApiResponseCircuitDto {
  success?: boolean;
  message?: string;
  result?: CircuitDto;
}
