/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserDto } from './userDto';

export interface AuthResponse {
  token?: string;
  user?: UserDto;
}
