/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CarConfigDto {
  /** @minLength 1 */
  engineName: string;
  /** @minLength 1 */
  engineType: string;
  enginePower: number;
  /** @minLength 1 */
  transmissionType: string;
  /** @minLength 1 */
  suspensionType: string;
  /** @minLength 1 */
  brakeType: string;
  maxSpeed: number;
  weight: number;
  length: number;
}
