/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CarDtoStatus = typeof CarDtoStatus[keyof typeof CarDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CarDtoStatus = {
  ALLOWED: 'ALLOWED',
  BANNED: 'BANNED',
  TEMPORARY_BANNED: 'TEMPORARY_BANNED',
  TERMINATED: 'TERMINATED',
} as const;
