/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CarDtoStatus } from './carDtoStatus';
import type { CarConfigDto } from './carConfigDto';

export interface CarDto {
  id?: string;
  name?: string;
  carNumber?: number;
  imageUrl?: string;
  status?: CarDtoStatus;
  location?: string;
  inResearch?: boolean;
  configuration?: CarConfigDto;
}
