/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CircuitDto {
  id?: string;
  name?: string;
  country?: string;
  city?: string;
  length?: number;
  layoutUrl?: string;
  lapRecord?: string;
  imageUrl?: string;
  firstParticipationYear?: number;
  numberOfCorners?: number;
  description?: string;
}
