/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DriverDto {
  id?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  broadcastName?: string;
  acronym?: string;
  driverNumber?: number;
  imageUrl?: string;
  countryCode?: string;
}
