/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RaceSequenceDtoStatus = typeof RaceSequenceDtoStatus[keyof typeof RaceSequenceDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaceSequenceDtoStatus = {
  PLANNED: 'PLANNED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
} as const;
