/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RaceSequenceSaveRequestSequenceType } from './raceSequenceSaveRequestSequenceType';
import type { CarConfigDto } from './carConfigDto';

export interface RaceSequenceSaveRequest {
  id?: string;
  sequenceType: RaceSequenceSaveRequestSequenceType;
  driverId: string;
  circuitId: string;
  carId: string;
  /** @minItems 1 */
  selectedCompounds: string[];
  customLapCount?: number;
  weatherInfo?: string;
  customCarSetup?: CarConfigDto;
}
