/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RaceSequenceDtoSequenceType } from './raceSequenceDtoSequenceType';
import type { RaceSequenceDtoStatus } from './raceSequenceDtoStatus';
import type { CarConfigDto } from './carConfigDto';

export interface RaceSequenceDto {
  id?: string;
  sequenceType?: RaceSequenceDtoSequenceType;
  status?: RaceSequenceDtoStatus;
  driverId?: string;
  driverName?: string;
  driverNumber?: number;
  circuitId?: string;
  circuitName?: string;
  defaultLapCount?: number;
  weatherInfo?: string;
  carId?: string;
  carName?: string;
  selectedCompounds?: string[];
  carSetupSnapshot?: CarConfigDto;
}
