/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RaceSequenceSaveRequestSequenceType = typeof RaceSequenceSaveRequestSequenceType[keyof typeof RaceSequenceSaveRequestSequenceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaceSequenceSaveRequestSequenceType = {
  RACE_WEEKEND: 'RACE_WEEKEND',
  TESTING: 'TESTING',
} as const;
