/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TeamCreateRequest {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  description?: string;
  /** @minLength 1 */
  hqLocation: string;
  logoUrl?: string;
}
