/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TeamDto {
  id?: string;
  name?: string;
  description?: string;
  hqLocation?: string;
  logoUrl?: string;
  inviteCode?: string;
}
