/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserDto {
  id?: string;
  operatorName?: string;
  callSign?: string;
  username?: string;
}
