/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseCarDto,
  ApiResponseCircuitDto,
  ApiResponseDriverDto,
  ApiResponseListCarDto,
  ApiResponseListCircuitDto,
  ApiResponseListDriverDto,
  CarCreateRequest,
  CircuitCreateRequest,
  DriverCreateRequest
} from '../../models';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getDrivers = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseListDriverDto>(
      {url: `/assets/drivers`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDriversQueryKey = () => {
    return [
    `/assets/drivers`
    ] as const;
    }

    
export const getGetDriversQueryOptions = <TData = Awaited<ReturnType<typeof getDrivers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDrivers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDriversQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDrivers>>> = ({ signal }) => getDrivers(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDrivers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDriversQueryResult = NonNullable<Awaited<ReturnType<typeof getDrivers>>>
export type GetDriversQueryError = unknown


export function useGetDrivers<TData = Awaited<ReturnType<typeof getDrivers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDrivers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDrivers>>,
          TError,
          Awaited<ReturnType<typeof getDrivers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDrivers<TData = Awaited<ReturnType<typeof getDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDrivers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDrivers>>,
          TError,
          Awaited<ReturnType<typeof getDrivers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDrivers<TData = Awaited<ReturnType<typeof getDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDrivers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDrivers<TData = Awaited<ReturnType<typeof getDrivers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDrivers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDriversQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const createDriver = (
    driverCreateRequest: DriverCreateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseDriverDto>(
      {url: `/assets/drivers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: driverCreateRequest, signal
    },
      options);
    }
  


export const getCreateDriverMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDriver>>, TError,{data: DriverCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDriver>>, TError,{data: DriverCreateRequest}, TContext> => {

const mutationKey = ['createDriver'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDriver>>, {data: DriverCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createDriver(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDriverMutationResult = NonNullable<Awaited<ReturnType<typeof createDriver>>>
    export type CreateDriverMutationBody = DriverCreateRequest
    export type CreateDriverMutationError = unknown

    export const useCreateDriver = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDriver>>, TError,{data: DriverCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDriver>>,
        TError,
        {data: DriverCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateDriverMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getCircuits = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseListCircuitDto>(
      {url: `/assets/circuits`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCircuitsQueryKey = () => {
    return [
    `/assets/circuits`
    ] as const;
    }

    
export const getGetCircuitsQueryOptions = <TData = Awaited<ReturnType<typeof getCircuits>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCircuits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCircuitsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCircuits>>> = ({ signal }) => getCircuits(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCircuits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCircuitsQueryResult = NonNullable<Awaited<ReturnType<typeof getCircuits>>>
export type GetCircuitsQueryError = unknown


export function useGetCircuits<TData = Awaited<ReturnType<typeof getCircuits>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCircuits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCircuits>>,
          TError,
          Awaited<ReturnType<typeof getCircuits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCircuits<TData = Awaited<ReturnType<typeof getCircuits>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCircuits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCircuits>>,
          TError,
          Awaited<ReturnType<typeof getCircuits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCircuits<TData = Awaited<ReturnType<typeof getCircuits>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCircuits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCircuits<TData = Awaited<ReturnType<typeof getCircuits>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCircuits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCircuitsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const createCircuit = (
    circuitCreateRequest: CircuitCreateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseCircuitDto>(
      {url: `/assets/circuits`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: circuitCreateRequest, signal
    },
      options);
    }
  


export const getCreateCircuitMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCircuit>>, TError,{data: CircuitCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCircuit>>, TError,{data: CircuitCreateRequest}, TContext> => {

const mutationKey = ['createCircuit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCircuit>>, {data: CircuitCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCircuit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCircuitMutationResult = NonNullable<Awaited<ReturnType<typeof createCircuit>>>
    export type CreateCircuitMutationBody = CircuitCreateRequest
    export type CreateCircuitMutationError = unknown

    export const useCreateCircuit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCircuit>>, TError,{data: CircuitCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCircuit>>,
        TError,
        {data: CircuitCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateCircuitMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getCars = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseListCarDto>(
      {url: `/assets/cars`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCarsQueryKey = () => {
    return [
    `/assets/cars`
    ] as const;
    }

    
export const getGetCarsQueryOptions = <TData = Awaited<ReturnType<typeof getCars>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCars>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCarsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCars>>> = ({ signal }) => getCars(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCars>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCarsQueryResult = NonNullable<Awaited<ReturnType<typeof getCars>>>
export type GetCarsQueryError = unknown


export function useGetCars<TData = Awaited<ReturnType<typeof getCars>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCars>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCars>>,
          TError,
          Awaited<ReturnType<typeof getCars>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCars<TData = Awaited<ReturnType<typeof getCars>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCars>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCars>>,
          TError,
          Awaited<ReturnType<typeof getCars>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCars<TData = Awaited<ReturnType<typeof getCars>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCars>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCars<TData = Awaited<ReturnType<typeof getCars>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCars>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCarsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const createCar = (
    carCreateRequest: CarCreateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponseCarDto>(
      {url: `/assets/cars`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: carCreateRequest, signal
    },
      options);
    }
  


export const getCreateCarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCar>>, TError,{data: CarCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCar>>, TError,{data: CarCreateRequest}, TContext> => {

const mutationKey = ['createCar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCar>>, {data: CarCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCar(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCarMutationResult = NonNullable<Awaited<ReturnType<typeof createCar>>>
    export type CreateCarMutationBody = CarCreateRequest
    export type CreateCarMutationError = unknown

    export const useCreateCar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCar>>, TError,{data: CarCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCar>>,
        TError,
        {data: CarCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateCarMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    